datasets:
  raw:
    opportunity:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/attrition/Spring_Oppty_Data.csv
      driver_params: {}

    product:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/attrition/springboard_illst_prd_dat.csv
      driver_params: {}
  cleaned:
    opportunity:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/attrition/Spring_Oppty_Data.parquet
      driver_params: {}

    product:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/attrition/springboard_illst_prd_dat.parquet
      driver_params: {}
  processed:
    attrition:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/attrition.parquet
      driver_params: {}
  train:
    attrition:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/attrition/features.parquet
        driver_params: {}

      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/attrition/target.parquet
        driver_params: {}
  test:
    attrition:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/attrition/features.parquet
        driver_params: {}

      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/attrition/target.parquet
        driver_params: {}
  score:
    attrition:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/attrition/scored_output.parquet
        driver_params: {}
